cpuguy83/go-md2man

mangen/mangen.go

When emitting .RS, also emit .RE to close the indentation.
I found this while trying to understand the docker man pages. :-)

Fixed BlockCode().

---

.gitignore
md2man.go
md2man/md2man.go
md2man/roff.go

d92bbe0a08731ac0747acbda45810ea3ab41d10c moved things from mangen into
the root subdir and changed the package to main. While this makes
sense for this utility others use go-md2man to generate docs automatically.
Instead of building a binary to do it. Move roff back out to a package
which can get included and used by others.
Including github.com/cpuguy83/go-md2man seems reasonable but has 2
problems.
1) now you likely have two `func main()` in package main
2) go-md2man defined `in` and `out` flags which would then show up in
auto generated lists of flags in these other projects

md2man usable as a library (again)

---

md2man/roff.go

* Disable hyphenation
* Disable justification (adjust text to left margin only)
* Fix output for bulleted lists and numbered lists
* Escape initial apostrophe and period to prevent a line of text
from being misinterpreted as a request/macro, leading to
"warning: macro 'xxx' not defined" and missing text.
----
I ran into problems with two of the man pages from [Hugo](https://github.com/spf13/hugo) and [Cobra](https://github.com/spf13/cobra), hence this pull request.  Many thanks!

Improve man page rendering

---

go-md2man.1.md
md2man.go

I think this makes it easy to use :smile:

use stdio for default input and output

---

md2man/roff.go

I suggest this for improving the readability of Docker's man pages.
If you have considered that and intentionally skipping the link content, please close this PR :sweat_smile:

improve link

---

README.md
vendor.yml
vendor/github.com/russross/blackfriday/LICENSE.txt
vendor/github.com/russross/blackfriday/README.md
vendor/github.com/russross/blackfriday/block.go
vendor/github.com/russross/blackfriday/html.go
vendor/github.com/russross/blackfriday/inline.go
vendor/github.com/russross/blackfriday/latex.go
vendor/github.com/russross/blackfriday/markdown.go
vendor/github.com/russross/blackfriday/smartypants.go
vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
vendor/github.com/shurcooL/sanitized_anchor_name/README.md
vendor/github.com/shurcooL/sanitized_anchor_name/main.go

I used [govendor](https://github.com/kardianos/govendor), but not sticking to it.
Please let me know if you like other vendoring tool

add vendor

---

md2man/roff.go

Adds additional indentation to support nesting of lists. Uses a stack to
keep track of numbering for ordered lists.
Fixes #18

Improve rendering of nested lists

---

md2man/roff.go
md2man/roff_test.go

Fixes: #34 
Tables were not being rendered correctly with the v2 blackfriday API,
including a nil pointer deref.
Signed-off-by: Phil Estes <estesp@gmail.com>

Fix table parsing/processing for v2

---

md2man/roff.go
md2man/roff_test.go

Since the switch to blackfriday v2, links are rendered incorrectly: link target and link text are contatenated together, like this:
Input:
the [Docker documentation](https://docs.docker.com/) for
Output:
the \n\\[la]https://docs.docker.com/Docker documentation\\[ra] for
Fix this, and provide a test case.
While at it, fix the contatenation of unhandled errors due to missing newline.
Cc: @estesp

Fix links rendering for v2

---

md2man/roff.go
md2man/roff_test.go

Hi, I stumbled into this issue when I was working on improving other man pages that are using this library to convert them from Markdown. However, no matter what I did, it was generating the wrong output when a tilde (~) was in the file. So, I removed it from the escaped characters and added a unit test for the escaped characters (including not escaping the tilde).
This PR resolves #26

Remove escaping tilde character

---

go.mod

The codebase is compatible with Go 1.12.

chore: set go minimal version to 1.11

---

md2man/roff.go
md2man/roff_test.go

The following valid markdown code:
Some term (DT)
: Description (DD1).
: Also description (DD2).
is currently not handled correctly, resulting in this roff output
.TP
Some term (DT)
Description (DD1).
.TP
Also description (DD2).
In other words, the second definition description (DD2) is
misrepresented as a separate definition title.
This happens because the code is not looking into ListTypeTerm flag
(perhaps it was not supported at the time of writing?), instead
alternating between DT and DD (assuming DD goes after DT and vice
versa), which is not the case if we have two DTs.
The fix is to check the ListTypeTerm flag: if set, this is a DT,
otherwise a DD.
Unfortunately we still have to use a state variable. This is because the
first DD should follow the DT immediately (i.e. no extra …

Fix handling multiple definition descriptions

---

.github/workflows/test.yml
Makefile

0. Add golangci-lint job (which used to be part of Travis-CI but was not moved over to GHA).
1. Update Go versions used in tests to current stable releases
(plus 1.13 which is still used by Moby).
2. Explicitly specify ubuntu version used.
3. Bump actions/setup-go to v2.

Refresh and improve CI

---

md2man/roff.go
md2man/roff_test.go

blackfriday v2 introduced "HTMLSpan" as a node-type, causing go-md2man
to produce warnings as it didn't have specific handling for these nodes.
This patch makes go-md2man ignore these node types (e.g. <span> elements,
or <svg>), and skip the element themselves (only rendering their content,
if any), to prevent go-md2man printing noisy warnings during generation:
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
WARNING: go-md2man does not handle node type HTMLSpan
...

Ignore unknown HTML tags to prevent noisy warnings

---

md2man/roff.go
md2man/roff_test.go

relates to / addresses https://github.com/docker/cli/issues/2985
Before this change, markup inside a table cell would introduce a newline, which resulted in those parts creating a new table row/cell:
┌───────────────────────────────┬───────────────────────────┐
│Col1                           │ Col2                      │
├───────────────────────────────┼───────────────────────────┤
│row|one                        │ Col1 should not wrap.     │
├───────────────────────────────┼───────────────────────────┤
│row two                        │ no                        │
├───────────────────────────────┼───────────────────────────┤
│|                              │                           │
├───────────────────────────────┼───────────────────────────┤
│wrap                           │ …

Fix inline markup causing table cells to split

---

md2man/roff.go
md2man/roff_test.go

Currently, we escape a few characters, such as
* `-` (dash) becomes `\-` (arithmetic minus sign)
* `_` (underscore) becomes `\_` (underline character)
* `&` (ampersand) becomes `\&` (zero-width space!)
As a result, we have two bugs:
1. All `&` characters disappear from the resulting man page.
2. Dashes are quite longer, and underscores becomes underlines (the
latter are lower). This is not reflected in text output, only in PDF
etc, and in most cases (like file names, command line options etc)
does not look good.
In fact, the only character that needs escaping is the backslash itself.
This is what this patch does, together with fixes to expected test
output.
The following commands were used to generate the example PDFs:
```console
$ bin/go-md2man < go-md2man.1.md > go-md2man.1
$ man -Tpdf …
```

Do not escape dash, underscore, and ampersand

---

.github/workflows/test.yml

Matrix var was not right and so it always installed go as if the version was empty.

Fix go version var in ci yaml

---

md2man/roff.go
md2man/roff_test.go

This PR improves link rendering in the manpages.
Escape hyphens in link destinations to prevent wrapping in the rendered manpage.
When links are wrapped it is neither possible to copy them nor will
the destination resolve properly in terminals which make them clickable.
See also https://liw.fi/manpages/#using-fonts

Improve Link Rendering

---

md2man/roff.go
md2man/roff_test.go

Motivated by https://github.com/containers/image/issues/2128 .
Run the tests with `-v` to see that there are no warnings.

Don't warn on top-level comments

---

md2man/roff.go
md2man/roff_test.go

When a table is present we need to instruct groff to enable the table preprocessor.
This surpresses warnings from groff.
Fixes #99

Prepend table preprocessor

---

md2man/roff.go
md2man/roff_test.go

Given this input:
> ```
> some code
> ```
We were adding an additional newline character before the code close tag even though the code block by definition already includes that newline.
e.g., blackfriday is hadning us `some code\n` as the literal content of the code block.
fixes #47

Fix trailing newline in code blocks

---

md2man/roff.go
md2man/roff_test.go

Given an input like so:
```markdown
'foo'
'bar'
```
We should be escaping both opening `'`.
Before this change only the first was escaped because we only look at the first character of a `[]byte` and did not account for newlines.
Fixes #110

Fix escape characters for content with newline

---

md2man/debug.go
md2man/md2man.go

Documentation on the shape of the markdown AST produced by the blackfriday parser is rather sparse. Add a decorator for renderers which dumps the visited AST nodes to stderr, interleaved with the renderer output, to help with debugging the roff renderer.
<details><summary>Example</summary>
<p>
```markdown
Definition title
: Definition description one
: And two
: And three
```
```
+ Document: '' 
+ List: '' ListTypeDefinition|ListItemBeginningOfList
+ Item: '' ListTypeDefinition|ListTypeTerm|ListItemBeginningOfList
>> "\n.TP\n"
+ Paragraph: '' 
+ Text: 'Definition title' 
>> "Definition title"
- Paragraph: '' 
- Item: '' ListTypeDefinition|ListTypeTerm|ListItemBeginningOfList
>> "\n"
+ Item: '' ListTypeDefinition
+ Paragraph: '' 
+ Text: 'Definition descr...' 
>> "Definition description …
```

Add debugging output for renderer

---

md2man/roff.go

The `firstDD` renderer state flag is not required. All list items are AST siblings so the first definition can be discriminated from subsequent definitions by checking if its previous sibling is a definition term.
The `extensions` field of the renderer is effectively a constant. It is assigned to once in the constructor and never touched again. Make it actually constant.

Reduce the amount of state the renderer needs to track

---

md2man/roff.go
md2man/roff_test.go

- Fixes #46 
Suppress `.PP` tags immediately following headers, and transform the first hyphen in the `NAME` section text to `\-` so that [generated man-pages follow the conventions required for proper indexing.](https://man7.org/linux/man-pages/man7/groff_man.7.html#:~:text=For%20example%2C%20a,be%20properly%20indexed.)
This does not affect the typeset output of man pages.

Emit a NAME section properly formatted for whatis parsing

---

go-md2man.1.md
md2man/roff.go
md2man/roff_test.go

The AST hierarchy for a list item is always `List` > `Item` > `Paragraph`. Emit newlines when visiting the `Paragraph` node instead of the `Item` and `List` so that `Item`s with multiple `Paragraphs` and nested `Lists` correctly render with just the right number of line breaks.
Update the man page to show off the new feature.
Stop over-indenting lists which are not nested inside a list item.
- Fixes #107 
- Closes #116
<details><summary>Input</summary>
<p>
```markdown
test
====
text
**Term**
:   Def Autem repellendus recusandae sint deserunt non. Quas maxime delectus
suscipit quis facere doloribus. Rerum omnis provident unde non sapiente
magni.
**Long term**
:   Long definition
Multiple paragraphs
- including
- lists
:   Second definition
more text
1. ordered lists
Also multiple …
```

Fix rendering of lists

---

.github/workflows/test.yml

The current version is not compatible with go1.23

gha: update golangci-lint to v1.62.2

---

md2man.go
md2man/roff.go

- revert https://github.com/cpuguy83/go-md2man/pull/125
- relates to https://github.com/spf13/cobra/pull/2201#issuecomment-2543996680
This reverts commit 76076049c2eabc4093673224cdb3dbccd2b5db1d.

Preserve compatibility with go <= 1.17

---

README.md

The installation instructions should be corrected to use the `v2` module, which is the same as the module path in the `go.mod` file.
Add usage instructions for using go-md2man with the `go tool` for `go 1.24+`, refer to [go 1.24 release notes] and [tool dependencies] and [go module **tool** directive].
[go 1.24 release notes]: https://go.dev/doc/go1.24#go-command
[tool dependencies]: https://go.dev/doc/modules/managing-dependencies#tools
[go module **tool** directive]: https://go.dev/ref/mod#go-mod-file-tool

Update usage instructions and fix module path

---

md2man/roff.go
md2man/roff_test.go

Currently, when a long cell in the table is not the last (rightmost),
due to extra `\n` the rendering is broken, resulting in an extra row.
The fix is easy -- do not add `\n` after `T}` unless it's the last cell.
Add a test case, which (before the fix) is rendered like this:
...
│ robin                  │ red.                   │
├────────────────────────┼────────────────────────┤
│ Meerschweinchen a.k.a. │                        │
│ guinea pig             │                        │
├────────────────────────┼────────────────────────┤
│                        │ Varies.                │
└────────────────────────┴────────────────────────┘
With the fix, it is rendered correctly now:
...
│ robin                  │ red.                   │
├────────────────────────┼────────────────────────┤
│ …

Table rendering fix
